#ifndef __GPIO_ARIES_SETTING_H_
#define __GPIO_ARIES_SETTING_H_

#define S3C_GPIO_SETPIN_ZERO	0
#define S3C_GPIO_SETPIN_ONE 	1
#define S3C_GPIO_SETPIN_NONE	2

//	GPIO Initialization table
//	{pin number,	  pin conf, 	   pin value,			 pullup/down config, driver strength,	 slew rate}
static unsigned int jupiter_gpio_table[][6] =
{
#if 0 // UART interface is already set
	// GPA0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPA0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif	
#if defined(CONFIG_ARIES_NTT) // Modify NTT S1	
	{S5PV210_GPA0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
#if 0// UART interface is already set
	// GPA1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPA1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPA1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif

	{S5PV210_GPA0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	// GPB -----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPB(0),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(1),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(2),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(3),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(4),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(5),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(6),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPB(7),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPC0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPC0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPC1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPC1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPC1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPD0 ----------------------------------------------------------------------------------------------------------------
#if defined (CONFIG_LCD_NEC_uPD161224)
	{S5PV210_GPD0(0), S3C_GPIO_SFN(2),  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#else
	{S5PV210_GPD0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
	{S5PV210_GPD0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPD1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPD1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPD1(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPE0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPE0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPE1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPE1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_2X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPE1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

#if 0 // LCD interface is already set
	// GPF0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPF0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPF1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPF1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF1(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPF2 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPF2(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF2(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPF3 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPF3(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF3(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF3(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF3(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
	{S5PV210_GPF3(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPF3(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPG0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPG0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPG1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPG1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(2), S3C_GPIO_OUTPUT, S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG1(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPG2 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPG2(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG2(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPG3 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPG3(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPG3(6), S3C_GPIO_OUTPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPH0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPH0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPH1 ----------------------------------------------------------------------------------------------------------------
#ifdef CONFIG_KEPLER_AUDIO_A1026
	{S5PV210_GPH1(0), S3C_GPIO_OUTPUT, S3C_GPIO_SETPIN_ONE, S3C_GPIO_PULL_DOWN,	 S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(1), S3C_GPIO_OUTPUT, S3C_GPIO_SETPIN_ONE, S3C_GPIO_PULL_DOWN,	 S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 			 
#else
	{S5PV210_GPH1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif

#if defined(CONFIG_S5PC110_SIDEKICK_BOARD)
	{S5PV210_GPH1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#else
	{S5PV210_GPH1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
	{S5PV210_GPH1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH1(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPH2 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPH2(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH2(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

#if 1 // SIDEKICK_KEYPAD
	// GPH3 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPH3(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#else
	// GPH3 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPH3(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPH3(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
	// GPI -----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPI(0),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(1),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(2),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(3),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(4),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(5),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPI(6),  S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPJ0 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPJ0(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ0(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPJ1 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPJ1(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ1(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ1(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ1(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ1(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#if 0 // SIDEKICK_KEYPAD
	{S5PV210_GPJ1(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPJ2 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPJ2(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ2(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
#endif
	{S5PV210_GPJ2(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPJ3 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPJ3(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ3(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// GPJ4 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_GPJ4(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ4(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ4(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ4(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_GPJ4(4), S3C_GPIO_OUTPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP01 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_MP01(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP01(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP01(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP01(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP01(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP01(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP01(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP01(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP02 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_MP02(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP02(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP02(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP02(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP03 ----------------------------------------------------------------------------------------------------------------
	//{S5PV210_MP03(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP03(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP03(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP03(3), S3C_GPIO_OUTPUT, S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP03(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
          {S5PV210_MP03(5), S3C_GPIO_OUTPUT, S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP03(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP03(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP04 ----------------------------------------------------------------------------------------------------------------
	{S5PV210_MP04(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP04(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP04(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP05 ----------------------------------------------------------------------------------------------------------------
	//{S5PV210_MP05(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	{S5PV210_MP05(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP05(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP06 ----------------------------------------------------------------------------------------------------------------
	//{S5PV210_MP06(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP06(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 

	// MP07 ----------------------------------------------------------------------------------------------------------------
	//{S5PV210_MP07(0), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(1), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(2), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(3), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(4), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(5), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(6), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
	//{S5PV210_MP07(7), S3C_GPIO_INPUT,  S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_DRVSTR_1X, S3C_GPIO_SLEWRATE_FAST}, 
};


//	off part GPIO Sleep Control table
//	{pin number,	  sleep mode conf,	  sleep pullup/down config}
static unsigned int jupiter_sleep_gpio_table[][3] =
{
	// GPA0 -------------------------------------------------
	{S5PV210_GPA0(0), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_BT_UART_RXD
	{S5PV210_GPA0(1), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_BT_UART_TXD
	{S5PV210_GPA0(2), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_BT_UART_CTS
	{S5PV210_GPA0(3), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_BT_UART_RTS
	{S5PV210_GPA0(4), S3C_GPIO_SLP_PREV, S3C_GPIO_PULL_UP}, 		//GPIO_GPS_UART_RXD
	{S5PV210_GPA0(5), S3C_GPIO_SLP_PREV, S3C_GPIO_PULL_UP}, 		//GPIO_GPS_UART_TXD
	{S5PV210_GPA0(6), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE}, 	//GPIO_LED2_GREEN
	{S5PV210_GPA0(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN}, 	//NC
	

	// GPA1 -------------------------------------------------
	{S5PV210_GPA1(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_AP_RXD
	{S5PV210_GPA1(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_AP_TXD
	{S5PV210_GPA1(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_UP},	//GPIO_AP_FLM_RXD
	{S5PV210_GPA1(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_AP_FLM_TXD


	// GPB	-------------------------------------------------
	{S5PV210_GPB(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPB(1),  S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_UP},	//GPIO_MSENSE_nRST
	{S5PV210_GPB(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPB(3),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_BT_nRST
	{S5PV210_GPB(4),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_BOOT_MODE
	{S5PV210_GPB(5),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_BT_EN
	{S5PV210_GPB(6),  S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_LED2_RED
	{S5PV210_GPB(7),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_GPB7 (CAM_IO_EN)


	// GPC0 -------------------------------------------------
	{S5PV210_GPC0(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_REC_PCM_CLK
	{S5PV210_GPC0(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPC0(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_REC_PCM_SYNC
	{S5PV210_GPC0(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_REC_PCM_IN
	{S5PV210_GPC0(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_REC_PCM_OUT


	// GPC1 -------------------------------------------------
	{S5PV210_GPC1(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPC1(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPC1(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPC1(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPC1(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// GPD0 -------------------------------------------------
	{S5PV210_GPD0(0), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_LCD_BL_PWM
	{S5PV210_GPD0(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_VIBTONE_PWM
	{S5PV210_GPD0(2), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_LED1_BLUE
	{S5PV210_GPD0(3), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_LED1_RED

	// GPD1 -------------------------------------------------
	{S5PV210_GPD1(0), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_CAM_SDA_29V
	{S5PV210_GPD1(1), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_CAM_SCL_29V

	{S5PV210_GPD1(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_OJ_SDA_28V	
	{S5PV210_GPD1(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_OJ_SCL_28V
	
	{S5PV210_GPD1(4), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_TSP_SDA_28V
	{S5PV210_GPD1(5), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_TSP_SCL_28V

	// GPE0 -------------------------------------------------
	{S5PV210_GPE0(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_PCLK
	{S5PV210_GPE0(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_VSYNC
	{S5PV210_GPE0(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_HSYNC
	{S5PV210_GPE0(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D0
	{S5PV210_GPE0(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D1
	{S5PV210_GPE0(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D2
	{S5PV210_GPE0(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D3
	{S5PV210_GPE0(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D4

	// GPE1 -------------------------------------------------
	{S5PV210_GPE1(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D5
	{S5PV210_GPE1(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D6
	{S5PV210_GPE1(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_CAM_D7
	{S5PV210_GPE1(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_CAM_MCLK
	{S5PV210_GPE1(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// GPF0 -------------------------------------------------
	{S5PV210_GPF0(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_HSYNC
	{S5PV210_GPF0(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_VSYNC
	{S5PV210_GPF0(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_DE
	{S5PV210_GPF0(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_PCLK
	{S5PV210_GPF0(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D0
	{S5PV210_GPF0(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D1
	{S5PV210_GPF0(6), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D2
	{S5PV210_GPF0(7), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D3

	// GPF1 -------------------------------------------------
	{S5PV210_GPF1(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D4
	{S5PV210_GPF1(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D5
	{S5PV210_GPF1(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D6
	{S5PV210_GPF1(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D7
	{S5PV210_GPF1(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D8
	{S5PV210_GPF1(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D9
	{S5PV210_GPF1(6), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D10
	{S5PV210_GPF1(7), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D11

	// GPF2 -------------------------------------------------
	{S5PV210_GPF2(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D12
	{S5PV210_GPF2(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D13
	{S5PV210_GPF2(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D14
	{S5PV210_GPF2(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D15
	{S5PV210_GPF2(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D16
	{S5PV210_GPF2(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D17
	{S5PV210_GPF2(6), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D18
	{S5PV210_GPF2(7), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D19

	// GPF3 -------------------------------------------------
	{S5PV210_GPF3(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D20
	{S5PV210_GPF3(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D21
	{S5PV210_GPF3(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D22
	{S5PV210_GPF3(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_LCD_D23
	{S5PV210_GPF3(4), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_CODEC_LDO_EN
	{S5PV210_GPF3(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// GPG0 -------------------------------------------------
	{S5PV210_GPG0(0), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG0(1), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG0(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	// NC
	{S5PV210_GPG0(3), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG0(4), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG0(5), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG0(6), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC

	// GPG1 -------------------------------------------------
	{S5PV210_GPG1(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_CLK
	{S5PV210_GPG1(1), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_CMD
	{S5PV210_GPG1(2), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_nRST
	{S5PV210_GPG1(3), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_D0
	{S5PV210_GPG1(4), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_D1
	{S5PV210_GPG1(5), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_D2
	{S5PV210_GPG1(6), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_WLAN_SDIO_D3

	// GPG2 -------------------------------------------------
	{S5PV210_GPG2(0), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_CLK
	{S5PV210_GPG2(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_CMD
	{S5PV210_GPG2(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPG2(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_D0
	{S5PV210_GPG2(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_D1
	{S5PV210_GPG2(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_D2
	{S5PV210_GPG2(6), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_T_FLASH_D3

	// GPG3 -------------------------------------------------
	{S5PV210_GPG3(0), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_GPS_nRST
	{S5PV210_GPG3(1), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_GPS_PWR_EN
	{S5PV210_GPG3(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//OJ_NRST
	{S5PV210_GPG3(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_UP},		//GPIO_TA_CURRENT_SEL_AP
	{S5PV210_GPG3(4), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_BT_WAKE
	{S5PV210_GPG3(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//CAM_3M_EN
	{S5PV210_GPG3(6), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//CAM_3M_RST


	// GPI --------------------------------------------------
	{S5PV210_GPI(0),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_CODEC_I2S_CLK
	{S5PV210_GPI(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPI(2),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_CODEC_I2S_WS
	{S5PV210_GPI(3),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_CODEC_I3S_DI
	{S5PV210_GPI(4),  S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},		//GPIO_CODEC_I3S_DO
	{S5PV210_GPI(5),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPI(6),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// GPJ0 -------------------------------------------------
	{S5PV210_GPJ0(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_MSENSE_SCL_28V
	{S5PV210_GPJ0(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_MSENSE_SDA_28V
	{S5PV210_GPJ0(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_HWREV_MODE0
	{S5PV210_GPJ0(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_HWREV_MODE1
	{S5PV210_GPJ0(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_HWREV_MODE2
	{S5PV210_GPJ0(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_TOUCH_INT

	{S5PV210_GPJ0(6), S3C_GPIO_SLP_PREV, S3C_GPIO_PULL_NONE},   	//MICBIAS_EN2
	{S5PV210_GPJ0(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_HWREV_MODE3

	// GPJ1 -------------------------------------------------
	{S5PV210_GPJ1(0), S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE},	//PHONE_ON
	{S5PV210_GPJ1(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_VIBTONE_EN1
	{S5PV210_GPJ1(2), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//QWERTY_EN
	{S5PV210_GPJ1(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_TOUCH_EN
	{S5PV210_GPJ1(4), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_PS_ON
	{S5PV210_GPJ1(5), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_KBC0

	// GPJ2 -------------------------------------------------
	{S5PV210_GPJ2(0), S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE},	//GPIO_KBC1
	{S5PV210_GPJ2(1), S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE},	//GPIO_KBC2
	{S5PV210_GPJ2(2), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_KBC3
	{S5PV210_GPJ2(3), S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE},	//GPIO_KBC4
	{S5PV210_GPJ2(4), S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE},		//GPIO_KBC5
	{S5PV210_GPJ2(5), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_KBC6
	{S5PV210_GPJ2(6), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_KBC7
	{S5PV210_GPJ2(7), S3C_GPIO_SLP_INPUT,  S3C_GPIO_PULL_DOWN},	//NC

	// GPJ3 -------------------------------------------------
	{S5PV210_GPJ3(0), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_ALS_SDA_28V
	{S5PV210_GPJ3(1), S3C_GPIO_SLP_PREV, S3C_GPIO_PULL_NONE},	      //GPIO_EARPATH_SEL
	{S5PV210_GPJ3(2), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_ALS_SCL_28V
	{S5PV210_GPJ3(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPJ3(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_USB_SDA_28V
	{S5PV210_GPJ3(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_USB_SCL_28V
	{S5PV210_GPJ3(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_SDA_28V
	{S5PV210_GPJ3(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_SCL_28V

	// GPJ4 -------------------------------------------------
	{S5PV210_GPJ4(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_PMIC_SDA
	{S5PV210_GPJ4(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_GPJ4(2), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_MICBIAS_EN
	{S5PV210_GPJ4(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_PMIC_SCL
	{S5PV210_GPJ4(4), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_OJ_SHDN

	// MP01 -------------------------------------------------
	{S5PV210_MP01(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP01(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_CS_H
	{S5PV210_MP01(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP01(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP01(4), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_AP_NANDCS
	{S5PV210_MP01(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP01(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP01(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// MP02 -------------------------------------------------
	{S5PV210_MP02(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP02(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP02(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_MP022
	{S5PV210_MP02(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// MP03 -------------------------------------------------
	{S5PV210_MP03(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP03(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP03(2), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_MP032
	{S5PV210_MP03(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_PDA_ACTIVE
	{S5PV210_MP03(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_MP04
	{S5PV210_MP03(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_CP_nRST
	{S5PV210_MP03(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP03(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// MP04 -------------------------------------------------
	{S5PV210_MP04(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP04(1), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_CLK
	{S5PV210_MP04(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP04(3), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_SI
	{S5PV210_MP04(4), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_SDO
	{S5PV210_MP04(5), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_SDX
	{S5PV210_MP04(6), S3C_GPIO_SLP_OUT1,  S3C_GPIO_PULL_NONE},	//GPIO_GPS_CLK_EN
	{S5PV210_MP04(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//GPIO_OJ_MOTION

	// MP05 -------------------------------------------------
	{S5PV210_MP05(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//FUEL_SCL_18V
	{S5PV210_MP05(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//FUEL_SDA_18V
	{S5PV210_MP05(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_SCL_18V
	{S5PV210_MP05(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},	//GPIO_AP_SDA_18V
	{S5PV210_MP05(4), S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},	//AP_ACTIVE
	{S5PV210_MP05(5), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_MLCD_RST
	{S5PV210_MP05(6), S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},	//GPIO_DISPLAY_CS_H
	{S5PV210_MP05(7), S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},	//GPIO_UART_SEL

	// MP06 -------------------------------------------------
	{S5PV210_MP06(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP06(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC

	// MP07 -------------------------------------------------
	{S5PV210_MP07(0), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(2), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(3), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(4), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(5), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(6), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
	{S5PV210_MP07(7), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	//NC
};


//	alive part GPIO Sleep Control table
//	{pin number,	  sleep mode conf,	sleep pin value,	  sleep pullup/down config}
static unsigned int jupiter_sleep_alive_gpio_table[][4] =
{
//	{S5PV210_GPH0(0), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN}, //pwr hold
	{S5PV210_GPH0(1), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},
	{S5PV210_GPH0(2), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN}, //GPIO_PS_VOUT
	{S5PV210_GPH0(3), S3C_GPIO_OUTPUT,	S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE},	//GPIO_BUCK_1_EN_A
	{S5PV210_GPH0(4), S3C_GPIO_OUTPUT,	S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE},	//GPIO_BUCK_1_EN_B
	{S5PV210_GPH0(5), S3C_GPIO_OUTPUT,	S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE},	//GPIO_BUCK_2_EN
	{S5PV210_GPH0(6), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_DET_35
	{S5PV210_GPH0(7), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_AP_PMIC_IRQ
	
	{S5PV210_GPH1(0), S3C_GPIO_OUTPUT,	S3C_GPIO_SETPIN_ZERO, S3C_GPIO_PULL_NONE},      // CP_RST
	{S5PV210_GPH1(1), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP},	//CP_PWR_RST
	{S5PV210_GPH1(2), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},	//TFLASH_DETECT
	{S5PV210_GPH1(3), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_nINT_ONEDRAM_AP
	{S5PV210_GPH1(4), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP},	//INT_RESOUT
	{S5PV210_GPH1(5), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN},	//GPIO_GPH15
	{S5PV210_GPH1(6), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP},	      // VOL_DOWN
	{S5PV210_GPH1(7), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},
	
	{S5PV210_GPH2(0), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_UP},   	// VOL_UP
	{S5PV210_GPH2(1), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN},	//GPIO_KBC1  //EAR_SEND_END_2.5
	{S5PV210_GPH2(2), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},	//GPIO_KBC2
	{S5PV210_GPH2(3), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},
	{S5PV210_GPH2(4), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN}, //GPIO_BT_HOST_WAKE
	{S5PV210_GPH2(5), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_DOWN}, //GPIO_BT_HOST_WAKE
	{S5PV210_GPH2(6), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_nPOWER
	{S5PV210_GPH2(7), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_JACK_nINT

	{S5PV210_GPH3(0), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},	//GPIO_KBR0
	{S5PV210_GPH3(1), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_KBR1
	{S5PV210_GPH3(2), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_KBR2
	{S5PV210_GPH3(3), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},	//GPIO_KBR3
	{S5PV210_GPH3(4), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_T_FLASH_DETECT
	{S5PV210_GPH3(5), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_OK_KEY
	{S5PV210_GPH3(6), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE}, //GPIO_EAR_SEND_END
	{S5PV210_GPH3(7), S3C_GPIO_INPUT,	S3C_GPIO_SETPIN_NONE, S3C_GPIO_PULL_NONE},	// OK_KEY

};

#endif
